import MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.APlusResidualGateSupplyQueue

namespace MaleyLean
namespace Papers
namespace MinimalConditionsForAdmissibleConstruction

#eval kernelAPlusResidualGateSupplyQueuePriorities
#eval kernelAPlusResidualGateSupplyQueueGates
#eval kernelAPlusResidualGateSupplyQueueTargets
#eval kernelAPlusResidualGateSupplyQueueCallabilityTheorems
#eval kernelAPlusResidualGateSupplyQueueRequiredInputs
#eval kernelAPlusResidualGateSupplyQueueSuppliedFlags
#eval kernelAPlusResidualGateSupplyQueuePopulatedBool
#eval kernelAPlusResidualGateSupplyQueueAllSuppliedBool

#print axioms kernelAPlusResidualGateSupplyQueue_count_eq
#print axioms kernelAPlusResidualGateSupplyQueuePriorities_eq
#print axioms kernelAPlusResidualGateSupplyQueueGates_eq
#print axioms kernelAPlusResidualGateSupplyQueueSuppliedFlags_eq
#print axioms kernelAPlusResidualGateSupplyQueuePopulatedBool_eq_true
#print axioms kernelAPlusResidualGateSupplyQueueAllSuppliedBool_eq_true
#print axioms kernelAPlusResidualGateSupplyQueueAuditComplete_holds

end MinimalConditionsForAdmissibleConstruction
end Papers
end MaleyLean
