import MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.APlusProgressLedger

namespace MaleyLean
namespace Papers
namespace MinimalConditionsForAdmissibleConstruction

#eval kernelAPlusCurrentProgressTuple
#eval kernelAPlusDefinitionCarrierLeanAnchors
#eval kernelAPlusDirectLeanTheoremAnchors
#eval kernelAPlusConsequenceProjectionAnchors
#eval kernelAPlusResidualGateLeanAnchors

#print axioms kernelAPlusDefinitionCarrierRows_count_eq
#print axioms kernelAPlusDirectLeanTheoremRows_count_eq
#print axioms kernelAPlusConsequenceProjectionRows_count_eq
#print axioms kernelAPlusProgressHypothesisGateRows_count_eq
#print axioms kernelAPlusProgressCorpusClosureRows_count_eq
#print axioms kernelAPlusClosedOrAuditedRowCount_eq
#print axioms kernelAPlusResidualGateRowCount_eq
#print axioms kernelAPlusMathematicalClosurePercent_eq
#print axioms kernelAPlusCurrentProgressSnapshot_obligationRows_eq
#print axioms kernelAPlusCurrentProgressSnapshot_closedOrAuditedRows_eq
#print axioms kernelAPlusCurrentProgressSnapshot_residualGateRows_eq
#print axioms kernelAPlusCurrentProgressSnapshot_auditReadinessPercent_eq
#print axioms kernelAPlusCurrentProgressSnapshot_mathematicalClosurePercent_eq
#print axioms kernelAPlusResidualGateLeanAnchors_count_eq
#print axioms kernelAPlusProgressAuditComplete_holds

end MinimalConditionsForAdmissibleConstruction
end Papers
end MaleyLean
