import MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.APlusAuditRunners

namespace MaleyLean
namespace Papers
namespace MinimalConditionsForAdmissibleConstruction

#eval kernelAPlusFocusedAuditRunnerFiles
#eval kernelAPlusAggregateAuditRunnerFiles
#eval kernelAPlusAuditRunnerFiles
#eval kernelAPlusAuditRunnerFilesDuplicateFreeBool
#eval kernelAPlusAuditRunnerFilesPopulatedBool

#print axioms kernelAPlusFocusedAuditRunnerFiles_count_eq
#print axioms kernelAPlusAggregateAuditRunnerFiles_count_eq
#print axioms kernelAPlusAuditRunnerFiles_count_eq
#print axioms kernelAPlusAuditRunnerFiles_decomposes
#print axioms kernelAPlusFocusedAuditRunnerFilesDuplicateFreeBool_eq_true
#print axioms kernelAPlusAggregateAuditRunnerFilesDuplicateFreeBool_eq_true
#print axioms kernelAPlusAuditRunnerFilesDuplicateFreeBool_eq_true
#print axioms kernelAPlusFocusedAuditRunnerFilesPopulatedBool_eq_true
#print axioms kernelAPlusAuditRunnerFilesPopulatedBool_eq_true
#print axioms kernelAPlusAuditRunnerRegistryComplete_holds

end MinimalConditionsForAdmissibleConstruction
end Papers
end MaleyLean
